### ISSUE TITLE
Return types are inconsistent

### ISSUE THREAD

**Issue by iwburns** [iwburns/id-tree#4]
@Drakulix pulling you in on this, I hope you don't mind.  I wanted to get the opinion of a person who is actually using the library on this.

I recently noticed that `get` and `get_mut` in `Tree` both return `Option`s instead of `Result`s despite the fact that the caller could conceivably call either one of them with a `NodeId` that is no longer valid or belongs to another `Tree` instance.

I'm wondering if the above scenario (calling `get`/`get_mut` with an invalid `NodeId`) is enough of a big deal to merit a `Result` return type, or if returning `None` is okay when that happens.

On one hand, there really is no `Node` that matches the `NodeId` provided in that scenario, and the caller isn't attempting to change any state when calling that function, so returning a `None` value seems alright.  (The `Tree` is basically just saying, "Nope, that doesn't match anything, sorry").

On the other hand, though, it might be more helpful to return a `Result` with the appropriate error if the caller is in a situation where they don't actually know whether a given `Node` is in `Tree`-`A` or `Tree`-`B`.  In that scenario, I can see it being quite useful to know _why_ there isn't a `Node` in the given `Tree` that matches the `NodeId` provided.

Also, at this point I think making a change like this would require me to version bump up to 1.0.0.  It's definitely a breaking change, and I'm not certain it would be alright to just bump the minor version even though we're pre-1.0.0 right now.  Also, I'm not sure how cargo behaves pre-1.0.0.

**Comment by Drakulix** [comment]
Well the biggest different, is that the `Result` is must-use, but why would you ever use `get`/`get_mut`, if you do not plan to use the returned node anyway, so thats not important.

`Result` is not more difficult to `match`, destruct or to `unwrap` (which I am mostly doing anyway, since an invalid id is a hard error in my program). So from my perspective as a library user almost nothing changes. I get some additional information (if the function errors), but I can mostly keep all my code with minor tweaks.

I am in favor of changing the type, to make it more consistent and provide the same information everywhere.

Also `semver` is nice standard, that really helps dealing with dependency issues.
I am not a big fan of pre-1.0.0 versions anyway, there are other means of stating, that your library is `unstable`, `unfinished` or whatever feels like "its not 1.0.0" yet. Libraries are not big professional programs, where each version feels like a major release. If you do a breaking change, just make it 1.0, you should have probably started with that version, if you felt like putting it on crates.io anyway. ;)
So this should not a point relevant to this discussion.

**Comment by iwburns** [comment]
Yeah, I was already trying to adhere to `semver` to be honest, but I feel like I don't _fully_ understand the protocol for pre-1.0.0 versions.  In any case, I agree, it needs to be bumped to 1.0.0 asap so that the normal `semver` rules can take effect (and so that there's no confusion about what is and isn't a breaking change in pre-1.0.0 versions).

As for the rest of your reply: I agree with all of your points here.  It really seems like (apart from this being a breaking change) there's not much of a downside to switching to `Result` from `Option`.

I'm going to let this settle in my mind a bit (a day or so) just to see if I can think of any major reasons not to do this.  If you think of anything please let me know, and thanks so much for your input so far!

**Comment by Drakulix** [comment]
Done via #12 ?

**Comment by iwburns** [comment]
Well, #12 did merge, but it merged into the 1.0.0-release branch, which is where I'm holding everything until we've got everything written up for that release.  So the answer to your question is: yes but it's not on master yet, so I figured I would leave this up.
