### ISSUE TITLE
tree.root may become invalid

### ISSUE THREAD

**Issue by Drakulix** [iwburns/id-tree#7]
Removing the root node with any remove method does not reset tree.root to None.

root_node_id will return an invalid Id in that case.

**Comment by iwburns** [comment]
Wow, just looked through those methods and you're absolutely right.  I'll get on that later today/tonight.  I think there's some re-factoring that needs to happen in there as well so I'll do that at the same time.

Thanks for pointing this out!

**Comment by iwburns** [comment]
@Drakulix 0.2.6 is up on crates.io

**Comment by Drakulix** [comment]
Reopening because the situation is not completely resolved.

When doing `remove_node_lift_children` on the root node, `self.root` is cleared, although a new node might become node.

I am not sure, what happens when you lift multiple children to the root level? (do they become orphans?)
But if the root node only has one child, that child should become the new root and `self.root` should point to it.

**Comment by iwburns** [comment]
If the node doesn't have a parent (which is always the case with the root node) then it's the same as calling remove_node_orphan_children.

At least that's the current implementation. I can see where if there's only one child it should probably become the root, but then what happens if there are multiple children?

I'm not sure what should happen then, maybe an error, but that's a breaking change anyway because the current behavior is documented that way.

If we can come up with a behavior that makes sense I'm cool with changing it, buy it would have to wait for the 1.0.0 release (hopefully soon, I just want to get as many breaking changes as possible in that release so we don't need to push to 2.x.x right after).

On mobile so I'm sorry for any typos.
